export const AddJob = async (
  airtable_id : string,
  eventType: any,
  talentQuota: string,
  eventTitle: string,
  eventRef: string,
  eventDescription: string,
  eventDates: any,
  requiredAttendDay: any,
  address1: string,
  address2: string,
  city: string,
  state: any,
  zip: string,
  talentRate: string,
  clientRate: string,
  agencyFee: any,
  rateBasis: any,
  contactName: string,
  contactPhone: string,
  wardrobe: string,
  parking: string,
  makeup: string,
  travel: string,
  recap: string,
  social: string,
  additionalLocation: string,
  referrals: string,
  talentExpectations: string,
  cancellation: string,
  contacts: string,
  miscellaneous: string,
  clientAssigned: any,
  talentInvited: any,
  location: string,
  talentNote: string,
  booker_mail: string,
) => {
  console.log("talentNote", talentNote); 
  const res = await fetch("/api/add-job", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      id: airtable_id,
      eventType: Array.from(eventType).toString(),
      talentQuota,
      eventTitle,
      eventRef,
      eventDescription,
      eventDates,
      requiredAttendDay: Array.from(requiredAttendDay).toString(),
      address1,
      address2,
      city,
      state: Array.from(state).toString(),
      zip,
      talentRate,
      clientRate,
      agencyFee: Array.from(agencyFee).toString(),
      rateBasis: Array.from(rateBasis).toString(),
      contactName,
      contactPhone,
      wardrobe,
      parking,
      makeup,
      travel,
      recap,
      social,
      additionalLocation,
      referrals,
      talentExpectations,
      cancellation,
      contacts,
      miscellaneous,
      clientAssigned:clientAssigned,
      talentInvited,
      location,
      booker_mail,
      talentNote,
    }),
  });
  // const data = await res.json();
  console.log(res);

  const data = await res.json();
  if (res.status !== 200) return { status: false, data: data };
  return { status: true, data };
};
