export const Gender = [
  { label: "Female", value: "Female" },
  { label: "Male", value: "Male" },
];

export const HairColor = [
  { label: "Auburn Brown", value: "Auburn" },
  { label: "Black", value: "Black" },
  { label: "Blonde", value: "Blonde" },
  { label: "Brown", value: "Brown" },
  { label: "Dark Brown", value: "Dark Brown" },
  { label: "Dirty Blonde", value: "Dirty Blonde" },
  { label: "Golden Brown", value: "Golden Brown" },
  { label: "Honey Brown", value: "Honey Brown" },
  { label: "Light Brown", value: "ight Brown" },
  { label: "Red", value: "Red" },
  { label: "Strawberry Blonde", value: "Strawberry Blonde" },
];
export const EyeColor = [
  { label: "Black", value: "Black" },
  { label: "Brown", value: "Brown" },
  { label: "Blue/Green", value: "Blue/Green" },
  { label: "Blue", value: "Blue" },
  { label: "Dark Brown", value: "Dark Brown" },
  { label: "Green", value: "Green" },
  { label: "Light Brown", value: "ight Brown" },
  { label: "Hazel", value: "Hazel" },
];

export const Ethnicity = [
  { label: "Caucasian", value: "Caucasian" },
  { label: "African American", value: "African American" },
  { label: "Hispanic/Latino", value: "Hispanic/Latino" },
  { label: "Asian", value: "Asian" },
  {
    label: "Native American/Alaskan Native",
    value: "Native American/Alaskan Native",
  },
  { label: "Pacific Islander", value: "Pacific Islander" },
  { label: "Middle Eastern", value: "Middle Eastern" },
  { label: "Multiracial/Mixed", value: "Multiracial/Mixed" },
  { label: "Prefer not to say", value: "Prefer not to say" },
];

export const Languages = [
  { label: "Albanian", value: "Albanian" },
  { label: "American Sign Language", value: "American Sign Language" },
  { label: "Arabic", value: "Arabic" },
  { label: "Cantonese", value: "Cantonese" },
  { label: "Chinese", value: "Chinese" },
  { label: "Creole", value: "Creole" },
  { label: "English", value: "English" },
  { label: "Estonian", value: "Estonian" },
  { label: "Farsi", value: "Farsi" },
  { label: "French", value: "French" },
  { label: "German", value: "German" },
  { label: "Greek", value: "Greek" },
  { label: "Haitian Creole", value: "Haitian Creole" },
  { label: "Hindi", value: "Hindi" },
  { label: "Italian", value: "Italian" },
  { label: "Jamaican Patois", value: "Jamaican Patois" },
  { label: "Japanese", value: "Japanese" },
  { label: "Mandarin", value: "Mandarin" },
  { label: "Polish", value: "Polish" },
  { label: "Portuguese", value: "Portuguese" },
  { label: "Romanian", value: "Romanian" },
  { label: "Russian", value: "Russian" },
  { label: "Spanish", value: "Spanish" },
  { label: "Tagalog", value: "Tagalog" },
];

export const Height = [
  { label: `1' 0"` },
  { label: `1' 1"` },
  { label: `1' 2"` },
  { label: `1' 3"` },
  { label: `1' 4"` },
  { label: `1' 5"` },
  { label: `1' 6"` },
  { label: `1' 7"` },
  { label: `1' 8"` },
  { label: `1' 9"` },
  { label: `1' 10"` },
  { label: `1' 11"` },
  { label: `2' 0"` },
  { label: `2' 1"` },
  { label: `2' 2"` },
  { label: `2' 3"` },
  { label: `2' 4"` },
  { label: `2' 5"` },
  { label: `2' 6"` },
  { label: `2' 7"` },
  { label: `2' 8"` },
  { label: `2' 9"` },
  { label: `2' 10"` },
  { label: `2' 11"` },
  { label: `3' 0"` },
  { label: `3' 1"` },
  { label: `3' 2"` },
  { label: `3' 3"` },
  { label: `3' 4"` },
  { label: `3' 5"` },
  { label: `3' 6"` },
  { label: `3' 7"` },
  { label: `3' 8"` },
  { label: `3' 9"` },
  { label: `3' 10"` },
  { label: `3' 11"` },
  { label: `4' 0"` },
  { label: `4' 1"` },
  { label: `4' 2"` },
  { label: `4' 3"` },
  { label: `4' 4"` },
  { label: `4' 5"` },
  { label: `4' 6"` },
  { label: `4' 7"` },
  { label: `4' 8"` },
  { label: `4' 9"` },
  { label: `4' 10"` },
  { label: `4' 11"` },
  { label: `5' 0"` },
  { label: `5' 1"` },
  { label: `5' 2"` },
  { label: `5' 3"` },
  { label: `5' 4"` },
  { label: `5' 5"` },
  { label: `5' 6"` },
  { label: `5' 7"` },
  { label: `5' 8"` },
  { label: `5' 9"` },
  { label: `5' 10"` },
  { label: `5' 11"` },
  { label: `6' 0"` },
  { label: `6' 1"` },
  { label: `6' 2"` },
  { label: `6' 3"` },
  { label: `6' 4"` },
  { label: `6' 5"` },
  { label: `6' 6"` },
  { label: `6' 7"` },
  { label: `6' 8"` },
  { label: `6' 9"` },
  { label: `6' 10"` },
  { label: `6' 11"` },
];

export const Waist = Array.from({ length: 55 }, (_, i) =>
  new String((i + 40) / 2).toString()
);

export const Dresssize = Array.from({ length: 9 }, (_, i) =>
  new String((i) * 2).toString()
);

export const Hips = Array.from({ length: 55 }, (_, i) =>
  new String((i + 60) / 2).toString()
);

export const Shoesize = Array.from({ length: 31 }, (_, i) =>
  new String((i + 2) / 2).toString()
);

export const Bust = [
  "1",
  "2",
  "3",
  "6",
  "7",
  "8",
  "14",
  "15",
  "16",
  "17",
  "22",
  "23",
  "24",
  "30",
  "31",
  "32A",
  "34A",
  "36A",
  "38A",
  "40A",
  "32B",
  "34B",
  "36B",
  "38B",
  "40B",
  "42B",
  "44B",
  "46B",
  "32C",
  "34C",
  "36C",
  "38C",
  "40C",
  "42C",
  "44C",
  "46C",
  "32D",
  "34D",
  "36D",
  "38D",
  "40D",
  "42D",
  "44D",
  "46D",
  "32D",
  "34D",
  "36D",
  "38D",
  "40D",
  "42D",
  "44D",
  "46D",
  "32DD",
  "34DD",
  "36DD",
  "38DD",
  "40DD",
  "42DD",
  "44DD",
  "46DD",
  "32DDD",
  "34DDD",
  "36DDD",
  "38DDD",
  "40DDD",
  "42DDD",
  "44DDD",
  "46DDD",
];

export const TalentType = [
  "ALL",
  "ACTOR",
  "CHILD",
  "COMMERCIAL | LIFESTYLE",
  "MAKEUP | HAIR ARTIST",
  "MODEL",
  "MUSIC",
  "PHOTOGRAPHER | VIDEOGRAPHER",
  "PRODUCTION",
  "PROMOTIONAL TALENT",
];

export const AddTalentType = [
  "ACTOR",
  "CHILD",
  "COMMERCIAL | LIFESTYLE",
  "MAKEUP | HAIR ARTIST",
  "MODEL",
  "MUSIC",
  "PHOTOGRAPHER | VIDEOGRAPHER",
  "PRODUCTION",
  "PROMOTIONAL TALENT",
];

export const GenderType = [
  { label: "ALL", value: "ALL" },
  { label: "Female", value: "Female" },
  { label: "Male", value: "Male" },
];

export const HairColorType = [
  { label: "ALL", value: "ALL" },
  { label: "Auburn Brown", value: "Auburn Brown" },
  { label: "Black", value: "Black" },
  { label: "Blonde", value: "Blonde" },
  { label: "Brown", value: "Brown" },
  { label: "Dark Brown", value: "Dark Brown" },
  { label: "Dirty Blonde", value: "Dirty Blonde" },
  { label: "Golden Brown", value: "Golden Brown" },
  { label: "Honey Brown", value: "Honey Brown" },
  { label: "Light Brown", value: "ight Brown" },
  { label: "Red", value: "Red" },
  { label: "Strawberry Blonde", value: "Strawberry Blonde" },
];

export const EyeColorType = [
  { label: "ALL", value: "ALL" },
  { label: "Black", value: "Black" },
  { label: "Brown", value: "Brown" },
  { label: "Blue/Green", value: "Blue/Green" },
  { label: "Blue", value: "Blue" },
  { label: "Dark Brown", value: "Dark Brown" },
  { label: "Green", value: "Green" },
  { label: "Light Brown", value: "ight Brown" },
  { label: "Hazel", value: "Hazel" },
];

export const EthnicityType = [
  { label: "ALL", value: "ALL" },
  {
    label: "American Indian or Alaska Native",
    value: "American Indian or Alaska Native",
  },
  { label: "Asian", value: "Asian" },
  { label: "Black or African American", value: "Black or African American" },
  {
    label: "Native Hawaiian or Other Pacific Islander",
    value: "Native Hawaiian or Other Pacific Islander",
  },
  { label: "White", value: "White" },
  { label: "Hispanic or Latino", value: "Hispanic or Latino" },
  { label: "Other", value: "Other" },
];

export const LanguagesType = [
  { label: "ALL", value: "ALL" },
  { label: "Albanian", value: "Albanian" },
  { label: "American Sign Language", value: "American Sign Language" },
  { label: "Arabic", value: "Arabic" },
  { label: "Cantonese", value: "Cantonese" },
  { label: "Chinese", value: "Chinese" },
  { label: "Creole", value: "Creole" },
  { label: "English", value: "English" },
  { label: "Estonian", value: "Estonian" },
  { label: "Farsi", value: "Farsi" },
  { label: "French", value: "French" },
  { label: "German", value: "German" },
  { label: "Greek", value: "Greek" },
  { label: "Haitian Creole", value: "Haitian Creole" },
  { label: "Hindi", value: "Hindi" },
  { label: "Italian", value: "Italian" },
  { label: "Jamaican Patois", value: "Jamaican Patois" },
  { label: "Japanese", value: "Japanese" },
  { label: "Mandarin", value: "Mandarin" },
  { label: "Polish", value: "Polish" },
  { label: "Portuguese", value: "Portuguese" },
  { label: "Romanian", value: "Romanian" },
  { label: "Russian", value: "Russian" },
  { label: "Spanish", value: "Spanish" },
  { label: "Tagalog", value: "Tagalog" },
];

// export const EventType = [
//   { label: "Brand Training", value: "Brand Training" },
//   { label: "CASTING", value: "CASTING" },
//   { label: "Dry Off-Premise Sampling", value: "Dry Off-Premise Sampling" },
//   { label: "Event", value: "Event" },
//   { label: "Event (Female Models)", value: "Event (Female Models)" },
//   { label: "Golf Tournament", value: "Golf Tournament" },
//   { label: "Off-Premise Beer Sampling", value: "Off-Premise Beer Sampling" },
//   {
//     label: "Off-Premise Liquor Sampling",
//     value: "Off-Premise Liquor Sampling",
//   },
//   { label: "Off-Premise Wine Sampling", value: "Off-Premise Wine Sampling" },
//   { label: "On-Premise Beer Sampling", value: "On-Premise Beer Sampling" },
//   {
//     label: "On-Premise Beer Sampling (Feamle Talent)",
//     value: "On-Premise Beer Sampling (Feamle Talent)",
//   },
//   { label: "On-Premise Crawl", value: "On-Premise Crawl" },
//   {
//     label: "On-Premise Crawl (Female Talent)",
//     value: "On-Premise Crawl (Female Talent)",
//   },
//   { label: "On-Premise Liquor Sampling", value: "On-Premise Liquor Sampling" },
//   {
//     label: "On-Premise Liquor Sampling (Female Talent)",
//     value: "On-Premise Liquor Sampling (Female Talent)",
//   },
//   { label: "Photo Shoot", value: "Photo Shoot" },
//   { label: "Product Demo", value: "Product Demo" },
//   { label: "Tradeshow", value: "Tradeshow" },
//   { label: "Video/Photo Shoot", value: "Video/Photo Shoot" },
//   { label: "Tradeshow / Convention", value: "Tradeshow / Convention" },
//   { label: "Promotion", value: "Promotion" },
//   { label: "TV / Video / Film", value: "TV / Video / Film" },
// ];

export const SearchEventType = [
  { label: "ALL", value: "ALL" },
  { label: "Brand Training", value: "Brand Training" },
  { label: "CASTING", value: "CASTING" },
  { label: "Dry Off-Premise Sampling", value: "Dry Off-Premise Sampling" },
  { label: "Event", value: "Event" },
  { label: "Event (Female Models)", value: "Event (Female Models)" },
  { label: "Golf Tournament", value: "Golf Tournament" },
  { label: "Off-Premise Beer Sampling", value: "Off-Premise Beer Sampling" },
  {
    label: "Off-Premise Liquor Sampling",
    value: "Off-Premise Liquor Sampling",
  },
  { label: "Off-Premise Wine Sampling", value: "Off-Premise Wine Sampling" },
  { label: "On-Premise Beer Sampling", value: "On-Premise Beer Sampling" },
  {
    label: "On-Premise Beer Sampling (Feamle Talent)",
    value: "On-Premise Beer Sampling (Feamle Talent)",
  },
  { label: "On-Premise Crawl", value: "On-Premise Crawl" },
  {
    label: "On-Premise Crawl (Female Talent)",
    value: "On-Premise Crawl (Female Talent)",
  },
  { label: "On-Premise Liquor Sampling", value: "On-Premise Liquor Sampling" },
  {
    label: "On-Premise Liquor Sampling (Female Talent)",
    value: "On-Premise Liquor Sampling (Female Talent)",
  },
  { label: "Photo Shoot", value: "Photo Shoot" },
  { label: "Product Demo", value: "Product Demo" },
  { label: "Tradeshow", value: "Tradeshow" },
  { label: "Video/Photo Shoot", value: "Video/Photo Shoot" },
  // { label: "Tradeshow / Convention", value: "Tradeshow / Convention" },
  // { label: "Promotion", value: "Promotion" },
  // { label: "TV / Video / Film", value: "TV / Video / Film" },
];

export const EventType = [
  { label: "Brand Training", value: "Brand Training" },
  { label: "CASTING", value: "CASTING" },
  { label: "Dry Off-Premise Sampling", value: "Dry Off-Premise Sampling" },
  { label: "Event", value: "Event" },
  { label: "Event (Female Models)", value: "Event (Female Models)" },
  { label: "Golf Tournament", value: "Golf Tournament" },
  { label: "Off-Premise Beer Sampling", value: "Off-Premise Beer Sampling" },
  {
    label: "Off-Premise Liquor Sampling",
    value: "Off-Premise Liquor Sampling",
  },
  { label: "Off-Premise Wine Sampling", value: "Off-Premise Wine Sampling" },
  { label: "On-Premise Beer Sampling", value: "On-Premise Beer Sampling" },
  {
    label: "On-Premise Beer Sampling (Feamle Talent)",
    value: "On-Premise Beer Sampling (Feamle Talent)",
  },
  { label: "On-Premise Crawl", value: "On-Premise Crawl" },
  {
    label: "On-Premise Crawl (Female Talent)",
    value: "On-Premise Crawl (Female Talent)",
  },
  { label: "On-Premise Liquor Sampling", value: "On-Premise Liquor Sampling" },
  {
    label: "On-Premise Liquor Sampling (Female Talent)",
    value: "On-Premise Liquor Sampling (Female Talent)",
  },
  { label: "Photo Shoot", value: "Photo Shoot" },
  { label: "Product Demo", value: "Product Demo" },
  { label: "Tradeshow", value: "Tradeshow" },
  { label: "Video/Photo Shoot", value: "Video/Photo Shoot" },
  // { label: "Tradeshow / Convention", value: "Tradeshow / Convention" },
  // { label: "Promotion", value: "Promotion" },
  // { label: "TV / Video / Film", value: "TV / Video / Film" },
];

export const StateType = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District Of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const JOBSTATE = [
  "ALL",
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District Of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const FeeType = ["0%", "10%", "20%"];

export const RateType = ["Hourly", "Daily", "Total"];

export const JobStatus = [
  "Add to Website",
  "Add info to Booking",
  "Invite Talent",
  "Need to Book",
  "Added to Q",
  "Booked",
  "Reminded to Confirm",
  "2nd Reminder to Confirm",
  "Final Reminder to Confirm",
  "Talent Confirmed",
  "Send Booking info",
  "Package Sent to Client",
  "Info Sent",
  "Confirmed Info",
  "Recap Reminder Sent",
  "Final Recap Reminder Sent",
  "Need Receipt",
  "ATTENTION NEEDED",
  "Cancelled",
  "Complete",
  "Ready to Invoice",
  "HOLD",
  "NEED RESCHEDULE",
  "New Talent On-boarding",
  "NO CALL NO SHOW",
  "Not Executed - See Client Note",
  "Not Invoiced",
  "Not Invoiced - No Recap",
  "Partially Booked",
  "Pending Approval",
  "admin invoice",
  "Pending - Talent Expense Approval",
  "TEMPLATE",
  "Payment Sent",
  "Availability Check",
  "CANCELLATION FEE",
  "Payment to be issued on next Check Run",
];

export const Tags_type = [
  "50+",
  "Acting",
  "Band",
  "Bartender",
  "Beam",
  "Brand Ambassador",
  "CASAMIGOS OFF",
  "CASAMIGOS ON",
  "Casting Networks",
  "Constellation Brands",
  "Events",
  "GAINESVILLE",
  "HUSA",
  "JAGER",
  "MAB - TAMPA",
  "Makeup Artist",
  "Model",
  "MONSTER",
  "Newground",
  "NO ABC",
  "No HUSA Mike Madej",
  "No Liquor",
  "No MAB-Chris",
  "No Off-Premise Samplings",
  "No Promos",
  "NO PUBLIX",
  "Not 21",
  "Off-Premise Samplings",
  "On-Premise Samplings",
  "OSM",
  "Photographer",
  "Photoshoots",
  "Plus",
  "Pregnant",
  "Promotional",
  "Proximo Cristalino Tequila Trained",
  "RumbleOn",
  "Still Austin",
  "Sylist",
  "TAMPA",
  "Tanteo Team",
  "Tanteo Trained",
  "Titos",
  "TITOS LEAD",
  "TPA Off Premise",
  "TPA On Premise",
  "W-9 Only",
  "White Claw"
];

export const StatusType: any = {
  "Talent Confirmed Booking": "Confirmed",
  "Job Open": "Open",
  "Job Booked": "Booked",
  "Talent Booked, Needs to Confirm": "Need Confirm",
};

export const BookingType = [
  "Acting",
  "Atmosphere Model",
  "Brand Ambassador",
  "Fit Modeling",
  "Golf Tournaments",
  "Hand Modeling",
  "Influencer",
  "Make-Up Artist",
  "MC",
  "Off-premise beer & liquor samplings",
  "On-Air Host",
  "On-premise beer & liquor samplings",
  "Print Work",
  "Product Specialist",
  "Runway",
  "Swimsuit Modeling - Photoshoots",
  "Swimsuit Modeling - Tradeshows",
  "Sylist",
  "Trade show booth hostess/host",
  "Voiceover",
  "Mascot",
];

export const Certifications = [
  { label: "ATC", value: "ATC" },
  { label: "MAST", value: "MAST" },
  {
    label: "Nex Mexico Alcohol Server Permit",
    value: "Nex Mexico Alcohol Server Permit",
  },
  { label: "Other", value: "Other" },
  { label: "Serve Safe", value: "Serve Safe" },
  { label: "TABC", value: "TABC" },
  { label: "TIPS", value: "TIPS" },
];

export const Cities = [
  "Jacksonville",
  "Miami",
  "Tampa",
  "Orlando",
  "St. Petersburg",
  "Hialeah",
  "Tallahassee",
  "Fort Lauderdale",
  "Port St. Lucie",
  "Cape Coral",
  "Pembroke Pines",
  "Hollywood",
  "Miramar",
  "Gainesville",
  "Coral Springs",
  "Miami Gardens",
  "Clearwater",
  "Palm Bay",
  "Pompano Beach",
  "West Palm Beach",
  "Lakeland",
  "Davie",
  "Miami Beach",
  "Sunrise",
  "Plantation",
  "Boca Raton",
  "Deltona",
  "Largo",
  "Deerfield Beach",
  "Palm Coast",
  "Melbourne",
  "Boynton Beach",
  "Lauderhill",
  "Weston",
  "Fort Myers",
  "Kissimmee",
  "Homestead",
  "Tamarac",
  "Delray Beach",
  "Daytona Beach",
  "North Miami",
  "Wellington",
  "North Port",
  "Jupiter",
  "Ocala",
  "Port Orange",
  "Margate",
  "Coconut Creek",
  "Sanford",
  "Sarasota",
  "Pensacola",
  "Bradenton",
  "Palm Beach Gardens",
  "Pinellas Park",
  "Coral Gables",
  "Doral",
  "Bonita Springs",
  "Apopka",
  "Titusville",
  "North Miami Beach",
  "Oakland Park",
  "Fort Pierce",
  "North Lauderdale",
  "Cutler Bay",
  "Altamonte Springs",
  "St. Cloud",
  "Greenacres",
  "Ormond Beach",
  "Ocoee",
  "Hallandale Beach",
  "Winter Garden",
  "Aventura",
  "Los Angeles",
  "San Diego",
  "San Jose",
  "San Francisco",
  "Fresno",
  "Sacramento",
  "Long Beach",
  "Oakland",
  "Bakersfield",
  "Anaheim",
  "Santa Ana",
  "Riverside",
  "Stockton",
  "Chula Vista",
  "Irvine",
  "Fremont",
  "San Bernardino",
  "Modesto",
  "Fontana",
  "Oxnard",
  "Moreno Valley",
  "Huntington Beach",
  "Glendale",
  "Santa Clarita",
  "Garden Grove",
  "Oceanside",
  "Rancho Cucamonga",
  "Santa Rosa",
  "Ontario",
  "Lancaster",
  "Elk Grove",
  "Corona",
  "Palmdale",
  "Salinas",
  "Pomona",
  "Hayward",
  "Escondido",
  "Torrance",
  "Sunnyvale",
  "Orange",
  "Fullerton",
  "Pasadena",
  "Thousand Oaks",
  "Visalia",
  "Simi Valley",
  "Concord",
  "Roseville",
  "Victorville",
  "Santa Clara",
  "Vallejo",
  "Berkeley",
  "El Monte",
  "Downey",
  "Costa Mesa",
  "Inglewood",
  "Carlsbad",
  "San Buenaventura (Ventura)",
  "Fairfield",
  "West Covina",
  "Murrieta",
  "Richmond",
  "Norwalk",
  "Antioch",
  "Temecula",
  "Burbank",
  "Daly City",
  "Rialto",
  "Santa Maria",
  "El Cajon",
  "San Mateo",
  "Clovis",
  "Compton",
  "Jurupa Valley",
  "Vista",
  "South Gate",
  "Mission Viejo",
  "Vacaville",
  "Carson",
  "Hesperia",
  "Santa Monica",
  "Westminster",
  "Redding",
  "Santa Barbara",
  "Chico",
  "Newport Beach",
  "San Leandro",
  "San Marcos",
  "Whittier",
  "Hawthorne",
  "Citrus Heights",
  "Tracy",
  "Alhambra",
  "Livermore",
  "Buena Park",
  "Menifee",
  "Hemet",
  "Lakewood",
  "Merced",
  "Chino",
  "Indio",
  "Redwood City",
  "Lake Forest",
  "Napa",
  "Tustin",
  "Bellflower",
  "Mountain View",
  "Chino Hills",
  "Baldwin Park",
  "Alameda",
  "Upland",
  "San Ramon",
  "Folsom",
  "Pleasanton",
  "Union City",
  "Perris",
  "Manteca",
  "Lynwood",
  "Apple Valley",
  "Redlands",
  "Turlock",
  "Milpitas",
  "Redondo Beach",
  "Rancho Cordova",
  "Yorba Linda",
  "Palo Alto",
  "Davis",
  "Camarillo",
  "Walnut Creek",
  "Pittsburg",
  "South San Francisco",
  "Yuba City",
  "San Clemente",
  "Laguna Niguel",
  "Pico Rivera",
  "Montebello",
  "Lodi",
  "Madera",
  "Santa Cruz",
  "La Habra",
  "Encinitas",
  "Monterey Park",
  "Tulare",
  "Cupertino",
  "Gardena",
  "National City",
  "Rocklin",
  "Petaluma",
  "Huntington Park",
  "San Rafael",
  "La Mesa",
  "Arcadia",
  "Fountain Valley",
  "Diamond Bar",
  "Woodland",
  "Santee",
  "Lake Elsinore",
  "Porterville",
  "Paramount",
  "Eastvale",
  "Rosemead",
  "Hanford",
  "Highland",
  "Brentwood",
  "Novato",
  "Colton",
  "Cathedral City",
  "Delano",
  "Yucaipa",
  "Watsonville",
  "Placentia",
  "Glendora",
  "Gilroy",
  "Palm Desert",
  "Cerritos",
  "West Sacramento",
  "Aliso Viejo",
  "Poway",
  "La Mirada",
  "Rancho Santa Margarita",
  "Cypress",
  "Dublin",
  "Covina",
  "Azusa",
  "Palm Springs",
  "San Luis Obispo",
  "Ceres",
  "San Jacinto",
  "Lincoln",
  "Newark",
  "Lompoc",
  "El Centro",
  "Danville",
  "Bell Gardens",
  "Coachella",
  "Rancho Palos Verdes",
  "San Bruno",
  "Rohnert Park",
  "Brea",
  "La Puente",
  "Campbell",
  "San Gabriel",
  "Beaumont",
  "Morgan Hill",
  "Culver City",
  "Calexico",
  "Stanton",
  "La Quinta",
  "Pacifica",
  "Montclair",
  "Oakley",
  "Monrovia",
  "Los Banos",
  "Martinez",
];

export const InseamSize = Array.from({ length: 25 }, (_, i) =>
  new String(i + 20).toString()
);

export const SuitSize = [
  "40",
  "41",
  "36S",
  "37S",
  "38S",
  "39S",
  "40S",
  "41S",
  "42S",
  "43S",
  "44S",
  "45S",
  "46S",
  "36R",
  "37R",
  "38R",
  "39R",
  "40R",
  "41R",
  "42R",
  "43R",
  "44R",
  "45R",
  "46R",
  "47R",
  "48R",
  "49R",
  "50R",
  "51R",
  "52R",
  "53R",
  "54R",
  "36L",
  "37L",
  "38L",
  "39L",
  "40L",
  "41L",
  "42L",
  "43L",
  "44L",
  "45L",
  "46L",
  "47L",
  "48L",
  "49L",
  "50L",
  "51L",
  "52L",
  "53L",
  "54L",
];

export const SpecialSkills = [
  { label: "Bartender", value: "Bartender" },
  { label: "Costume Character", value: "Costume Character" },
  { label: "Dancer - Ballet", value: "Dancer - Ballet" },
  { label: "Dancer - Club", value: "Dancer - Club" },
  { label: "Dancer - Hip Hop", value: "Dancer - Hip Hop" },
];

export const PROFILESTATE = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District Of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const MinHourlyRate = [
  "$20.00",
  "$25.00",
  "$30.00",
  "$35.00",
  "$40.00",
  "$50.00",
  "$60.00",
  "$70.00",
  "$80.00",
  "$90.00",
  "$100 +",
];

export const MinDailyRate = [
  "$150.00",
  "$200.00",
  "$250.00",
  "$300.00",
  "$350.00",
  "$400.00",
  "$450.00",
  "$500.00",
  "$550.00",
  "$600.00",
  "$650.00",
  "$700 +",
];

export const SubjectArr = [
  "[title] INFO POSTED",
  "Availability Call for : [title]",
  "[title] Recap Not Received",
  "CONFIRMATION NEEDED [title]",
  "[title] INFO POSTED",
  "[title] INFO POSTED"
]

export const MessageArr = [
  `<p>Your information for your [event_type] has been posted online. You can view this information by going to the link below. It is EXTREMELY IMPORTANT that you EMAIL ME BACK so I know you have read and understand your booking info. ALERT: This event begins in one week or less, if you unconfirm this booking , you agree to a fine of $100. </p><br/><br/><p>[link]</p><p>Sincerely,</p><p>[signature]</p><p>VIEW ALL YOUR BOOKED JOBS HERE: ${process.env.NEXT_PUBLIC_SERVER_URI}/job-board/booked</p>`,
  `<p>Hello! If you haven't already, please respond and mark your availability for this job in the software. The client will be making decisions on talent to be booked shortly!&nbsp;</p><p><br></p><p>[link]</p><p><br></p><p>[signature]</p><p><br></p><p>VIEW ALL YOUR BOOKED JOBS HERE: ${process.env.NEXT_PUBLIC_SERVER_URI}/job-board/booked</p>`,
  `<p>[name],</p><p><br></p><p>Hello!&nbsp;We have not received your completed recap for this event. Please note that if the full detailed completed recap is not received we cannot bill the client for the event and you will not be paid for the event.&nbsp;</p><p><br></p><p>If the event was not completed as confirmed you will be charged a $100 cancellation/no show fee.&nbsp;</p><p><br></p><p>[link]:</p><p><br></p><p>[signature]</p><p><br></p><p>VIEW ALL YOUR BOOKED JOBS HERE: ${process.env.NEXT_PUBLIC_SERVER_URI}/job-board/booked</p>`,
  `<p>[name],</p><p>&nbsp;</p><p>You have been booked for [title]. Please go to the link below and click confirm on the booking page.&nbsp;</p><p>&nbsp;</p><p>EVENT: [title]</p><p>EVENT LINK: [link]&nbsp;</p><p>&nbsp;</p><p>THANK YOU!&nbsp;</p><p>[signature]</p><p><br></p><p>VIEW ALL YOUR BOOKED JOBS HERE: ${process.env.NEXT_PUBLIC_SERVER_URI}/job-board/booked</p>`,
  `<p>Your information for your [event_type] has been posted online. You can view this information by going to the link below. It is EXTREMELY IMPORTANT that you EMAIL ME BACK so I know you have thoroughly read and understand your booking info.&nbsp;</p><p><br></p><p>Please do not forget to call the store 48 hours prior to your sampling to confirm the sampling and make sure they have the product in stock.&nbsp;</p><p><br></p><p>Also note that you must complete the COVID-19 Waiver within 24 hours prior to your booking.&nbsp;&nbsp;</p><p><br></p><p>ALERT: This event begins in one week or less, if you unconfirm this booking , you agree to a fine of $100.</p><p><br></p><p>[link]</p><p><br></p><p>Sincerely,</p><p>[signature]</p><p><br></p><p>VIEW ALL YOUR BOOKED JOBS HERE: ${process.env.NEXT_PUBLIC_SERVER_URI}/job-board/booked</p>`,
  `<p>Your information for [title] has been posted online. You can view this information by going to the link below. It is EXTREMELY IMPORTANT that you EMAIL ME BACK so I know you have thoroughly read and understand your booking info.&nbsp;</p><p><br></p><p>EVENT LINK: [link]</p><p><br></p><p>***REMINDER - By confirming this booking you understand and agree to:</p><p><br></p><p>-Conduct yourself with propriety and dignity, and to do nothing that may injure the reputation and goodwill of M&amp;G or the client.</p><p><br></p><p>-Follow the EXACT dress code listed in this booking.</p><p><br></p><p>-Not use your cell phones during this booking unless it is an emergency or if you are taking quick pictures for your recap.</p><p><br></p><p>-Not drink alcoholic beverages, smoke or vape while at this booking or in uniform.</p><p><br></p><p>-Not have friends, family, etc. present at the working location unless you are under the age of 18.</p><p><br></p><p>-Work harmoniously with fellow models, talent and clients.</p><p><br></p><p>-A $100 rebooking and cancellation fee if you cancel this booking within 7 days of the start date or do not show up for this booking. (Medical &amp; Personal Emergencies are exempt from this fee with proper documentation)</p><p><br></p><p>-Help M&amp;G find an appropriate replacement if you have to cancel this booking within 7 days of the start date to avoid the $100 rebooking and cancellation fee.</p><p><br></p><p>-Arrive early this booking so that you are ready to work at the start time.</p><p><br></p><p>-A $15 fee will be deducted for every 15 minutes you are late to this booking. (Medical &amp; Personal Emergencies are exempt from this fee with proper documentation)</p><p><br></p><p>-Keep the on-site contact and M&amp;G informed if you are running behind. (call the on-site contact 1st and then M&amp;G)</p><p><br></p><p>-Turn in recaps, receipts or time sheets within 24 hours of the completion of this booking.</p><p><br></p><p>-Complete the COVID-19 Waiver within 24 hours prior to your booking.&nbsp;&nbsp;</p><p><br></p><p>Thank you,</p><p>[signature]</p><p><br></p><p>VIEW ALL YOUR BOOKED JOBS HERE: ${process.env.NEXT_PUBLIC_SERVER_URI}/job-board/booked</p>`
]